language: ruby
rvm:
- 2.2.0
script: RAILS_ENV=test bin/rake spec assets:precompile assets:clean
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 8a5bd3f6f114502e6ed60c9707592f92240d0b1fb9e6cb6b8f1b052e1206c231
cache:
  bundler: true
  apt: true
bundler_args: "--without development:production"
before_script:
- mkdir -p tmp/cache
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bin/rake db:create db:structure:load
